SET SERVEROUTPUT ON;

--test cases in art category table
EXECUTE ART_GALLERY_APP_ADMIN1.INSERT_ART_CATEGORY('Moulds');
EXECUTE ART_GALLERY_APP_ADMIN1.UPDATE_ART_CATEGORY(12, 'Ice moulds');
EXECUTE ART_GALLERY_APP_ADMIN1.VIEW_ART_CATEGORY;

--testcases in artwork table
EXECUTE ART_GALLERY_APP_ADMIN1.INSERT_ARTWORK(2,2,2,2,'yukta','good',120,'Available',utl_raw.cast_to_raw('/Users/bunny/DMDD_PROJECT/Images/tanner.webp'));
EXECUTE ART_GALLERY_APP_ADMIN1.UPDATE_ARTWORK(62,2,2,2,2,'Ramya','good',120,'Available',utl_raw.cast_to_raw('/Users/bunny/DMDD_PROJECT/Images/tanner.webp'));
EXECUTE ART_GALLERY_APP_ADMIN1.DELETE_ARTWORK(63);
EXECUTE ART_GALLERY_APP_ADMIN1.VIEW_ARTWORKS;

--test cases in online exhibition table
EXECUTE ART_GALLERY_APP_ADMIN1.INSERT_EXHIBITION(3,TO_DATE('2023/12/02 14:02:44', 'yyyy/mm/ddhh24:mi:ss'),TO_DATE('2023/12/06 14:02:44', 'yyyy/mm/ddhh24:mi:ss'),'Upcoming');
EXECUTE ART_GALLERY_APP_ADMIN1.UPDATE_EXHIBITION(4,1,TO_DATE('2023-05-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS'),TO_DATE('2023-05-05 18:00:00', 'YYYY-MM-DD HH24:MI:SS'),'Active');
EXECUTE ART_GALLERY_APP_ADMIN1.VIEW_EXHIBITIONS;

--test cases in users table
EXECUTE ART_GALLERY_APP_ADMIN1.INSERT_USER(2, 'hear.throb@example.com', 'johndoe', 'password', 'John', 'Doe', 'Software Developer', 'USA');
EXECUTE ART_GALLERY_APP_ADMIN1.UPDATE_USER(32, 2, 'hear.throb@example.com', 'newusername', 'newpassword', 'New', 'User', 'Specialty', 'Nationality');
EXECUTE ART_GALLERY_APP_ADMIN1.view_users_details;

--testcases in contacts table
EXECUTE ART_GALLERY_APP_ADMIN1.INSERT_CONTACT(32,'5849511873','BOSTON','MALDEN','BOSTON','MA','USA','03214');
EXECUTE ART_GALLERY_APP_ADMIN1.UPDATE_CONTACT(8,8,'9423547990','BOSTON','MALDEN','Natick','MA','USA','03214');
EXECUTE ART_GALLERY_APP_ADMIN1.VIEW_CONTACTS;

--views testcases for artist
SELECT * FROM ART_GALLERY_APP_ADMIN1.ARTIST_UPCOMING_EXHIBITIONS;
SELECT * FROM ART_GALLERY_APP_ADMIN1.ARTIST_ACTIVE_EXHIBITIONS;
SELECT * FROM ART_GALLERY_APP_ADMIN1.ARTIST_UNSOLD_ARTWORK;
SELECT * FROM ART_GALLERY_APP_ADMIN1.UNSHIPPED_ORDER_INFO;
SELECT * FROM ART_GALLERY_APP_ADMIN1.ARTIST_EXHIBITION;

--package testcase
EXECUTE ART_GALLERY_APP_ADMIN1.MANAGE_ARTWORKS.VIEW_ARTIST_ARTWORKS(2);
EXECUTE ART_GALLERY_APP_ADMIN1.MANAGE_ORDERS.update_order_status(6);

