PURGE RECYCLEBIN;

SET SERVEROUTPUT ON;
declare
    is_true number;
begin
    select count(*) 
    INTO IS_TRUE
    from dba_users where username='ART_GALLERY_APP_ADMIN1';
    IF IS_TRUE > 0
    THEN
    EXECUTE IMMEDIATE 'DROP USER ART_GALLERY_APP_ADMIN1 CASCADE';
    END IF;
END;
/

select * from dba_users where username='ART_GALLERY_APP_ADMIN1';

CREATE USER ART_GALLERY_APP_ADMIN1 IDENTIFIED BY Password123# QUOTA 200M ON DATA;

GRANT CONNECT TO ART_GALLERY_APP_ADMIN1 WITH ADMIN OPTION;

GRANT RESOURCE TO ART_GALLERY_APP_ADMIN1 WITH ADMIN OPTION;

GRANT CREATE VIEW TO ART_GALLERY_APP_ADMIN1 WITH ADMIN OPTION;

GRANT CREATE PROCEDURE TO ART_GALLERY_APP_ADMIN1 WITH ADMIN OPTION;

GRANT CREATE USER TO ART_GALLERY_APP_ADMIN1;

GRANT DROP USER TO ART_GALLERY_APP_ADMIN1;

GRANT CREATE SEQUENCE TO ART_GALLERY_APP_ADMIN1;

GRANT CREATE TABLE TO ART_GALLERY_APP_ADMIN1;



--SET SERVEROUTPUT ON;
--ALTER SYSTEM KILL SESSION 'ALL' IMMEDIATE;
----SELECT sid, serial#, username, osuser, machine FROM v$session;
--
--BEGIN
--EXECUTE IMMEDIATE 'DROP ROLE AdminRole';
--dbms_output.put_line('Objects dropped');
--EXCEPTION
--WHEN OTHERS
--THEN dbms_output.put_line('Error: ' || sqlerrm);
--END;
--/ 
--
--BEGIN
--EXECUTE IMMEDIATE 'DROP USER g_admin CASCADE';
--dbms_output.put_line('Objects dropped');
--EXCEPTION
--WHEN OTHERS
--THEN dbms_output.put_line('Error: ' || sqlerrm);
--END;
--/
--
--CREATE ROLE AdminRole IDENTIFIED BY April2023;
--CREATE USER g_admin IDENTIFIED BY Adminartgallery004; 
--
--GRANT CREATE VIEW TO g_admin WITH ADMIN OPTION;
--GRANT CREATE SESSION TO g_admin WITH ADMIN OPTION;
--GRANT CREATE ROLE TO g_admin WITH ADMIN OPTION;
--GRANT CREATE PROCEDURE TO g_admin WITH ADMIN OPTION;
--GRANT CREATE USER to g_admin;
--GRANT AdminRole to g_admin WITH ADMIN OPTION;
--GRANT gallery_admin TO g_admin WITH ADMIN OPTION;
--GRANT DROP ANY ROLE TO g_admin;
--GRANT DROP USER TO g_admin;
--GRANT DROP ANY TABLE TO g_admin;
--
--grant connect to g_admin WITH ADMIN OPTION;
--grant resource to g_admin;
--alter user g_admin quota 500M on data;
--
---- Grant privileges to ADMIN role
--GRANT ALL PRIVILEGES ON USER_ROLE TO g_admin;
--GRANT ALL PRIVILEGES ON USERS TO g_admin;
--GRANT ALL PRIVILEGES ON CONTACT TO g_admin;
--GRANT ALL PRIVILEGES ON SHIPPER TO g_admin;
--GRANT ALL PRIVILEGES ON ONLINE_EXHIBITION TO g_admin;
--GRANT ALL PRIVILEGES ON ORDERS TO g_admin;
--GRANT ALL PRIVILEGES ON ORDER_ITEMS TO g_admin;
--GRANT ALL PRIVILEGES ON ART_CATEGORY TO g_admin;
--GRANT ALL PRIVILEGES ON ARTWORK TO g_admin;
--
