--report to generate top 5 artist
WITH ranked_artists AS (
    SELECT u.userid, u.username AS artist_name, COUNT(DISTINCT a.artworkid) AS total_artworks_sold,
           DENSE_RANK() OVER (ORDER BY COUNT(DISTINCT a.artworkid) DESC) AS artist_rank
    FROM users u
    JOIN user_role ur ON u.roleid = ur.roleid
    JOIN artwork a ON u.userid = a.userid
    WHERE a.Status = 'Sold' AND ur.roleid = 2
    GROUP BY u.username, ur.rolename, u.userid
)
SELECT artist_name, artist_rank, total_artworks_sold
FROM ranked_artists
WHERE artist_rank <= 5;
 
--reports to generate trending artcategories
WITH trending_artcategory AS (
    SELECT ac.artcategory as artcategory_name, COUNT(a.artcategoryid) AS num_sold,
        DENSE_RANK() OVER (ORDER BY COUNT(DISTINCT a.artworkid) DESC) AS artcategory_rank
    FROM artwork a
    LEFT JOIN art_category ac ON a.artcategoryid = ac.artcategoryid 
    where a.status = 'Sold'
    GROUP BY a.artcategoryid,ac.artcategory
)
select artcategory_name, artcategory_rank, num_sold
from trending_artcategory
where artcategory_rank <= 3;

--Report for revenue generated by artist
SELECT TO_CHAR(TRUNC(o.OrderDateTime, 'MONTH'), 'Month') AS Month, SUM(o.TotalAmount) AS Revenue
FROM ORDERS o
JOIN ORDER_ITEMS oi ON o.OrderID = oi.OrderID
JOIN ARTWORK a ON oi.OrderItemsID = a.OrderItemsID
WHERE a.UserID = 16
AND EXTRACT(YEAR FROM o.OrderDateTime) = 2022
GROUP BY TRUNC(o.OrderDateTime, 'MONTH')
ORDER BY TRUNC(o.OrderDateTime, 'MONTH') ASC;

--Report to generate revenue for online_exhibition, artwork_in_general, total
SELECT 
  'online exhibition' AS Exhibition_Summary, 
  COALESCE(SUM(CASE WHEN ag.exhibitionid IS NOT NULL THEN ag.amount ELSE 0 END), 0) AS Revenue
FROM ARTWORK ag
LEFT JOIN ONLINE_EXHIBITION oe ON ag.exhibitionid = oe.exhibitionid
WHERE ag.status = 'Sold'
UNION
SELECT 
  'artwork in general' AS Exhibition_Summary, 
  SUM(CASE WHEN ag.exhibitionid IS NULL THEN ag.amount ELSE 0 END) AS Revenue
FROM ARTWORK ag
WHERE ag.status = 'Sold'
UNION
SELECT 
  'total' AS Exhibition_Summary, 
  SUM(CASE WHEN ag.status = 'Sold' THEN ag.amount ELSE 0 END) AS Revenue
FROM ARTWORK ag
WHERE ag.status = 'Sold';

--Report to generate top frequent customers
WITH FREQUENT_CUSTOMERS AS (
    SELECT u.USERID as customer_id,u.username AS customer_name, COUNT(oi.ORDERITEMSID) AS num_orders,
    DENSE_RANK() OVER (ORDER BY COUNT(DISTINCT oi.ORDERITEMSID) DESC) AS customer_rank
    FROM USERS u
    JOIN USER_ROLE ur ON u.ROLEID = ur.ROLEID
    JOIN ORDERS o ON u.USERID = o.USERID
    JOIN ORDER_ITEMS oi ON o.ORDERID = oi.ORDERID
    JOIN ARTWORK a ON oi.ORDERITEMSID = a.ORDERITEMSID
    WHERE ur.ROLENAME = 'Customer' AND a.STATUS = 'Sold'
    GROUP BY u.username, ur.rolename, u.userid, u.roleid
)
SELECT customer_name, customer_rank, num_orders
FROM frequent_customers
WHERE customer_rank <= 3;

