SET SERVEROUTPUT ON;

BEGIN
EXECUTE IMMEDIATE 'DROP ROLE ARTIST';
dbms_output.put_line('Objects dropped');
EXCEPTION
WHEN OTHERS
THEN dbms_output.put_line('Objects not found');
END;
/ 

BEGIN
EXECUTE IMMEDIATE 'DROP ROLE CUSTOMER';
dbms_output.put_line('Objects dropped');
EXCEPTION
WHEN OTHERS
THEN dbms_output.put_line('Objects not found');
END;
/ 

BEGIN
EXECUTE IMMEDIATE 'DROP USER ART_GALLERY_ARTIST CASCADE';
dbms_output.put_line('Objects dropped');
EXCEPTION
WHEN OTHERS
THEN dbms_output.put_line('Objects not found');
END;
/ 

BEGIN
EXECUTE IMMEDIATE 'DROP USER ART_GALLERY_CUSTOMER CASCADE';
dbms_output.put_line('Objects dropped');
EXCEPTION
WHEN OTHERS
THEN dbms_output.put_line('Objects not found');
END;
/

--CREATE  ROLE ARTIST IDENTIFIED BY April2023; 
--CREATE ROLE CUSTOMER IDENTIFIED BY April2023;



CREATE USER ART_GALLERY_ARTIST IDENTIFIED BY Artistartgallery004 QUOTA 200M ON DATA; 
CREATE USER ART_GALLERY_CUSTOMER IDENTIFIED BY Customerartgallery004 QUOTA 200M ON DATA; 



GRANT CONNECT TO ART_GALLERY_ARTIST;
GRANT CREATE PROCEDURE TO ART_GALLERY_ARTIST;
GRANT CREATE VIEW TO ART_GALLERY_ARTIST;
GRANT EXECUTE ON artist_actions_pkg TO ART_GALLERY_ARTIST;
GRANT EXECUTE ON MANAGE_ARTWORK TO ART_GALLERY_ARTIST;
GRANT EXECUTE ON MANAGE_ARTGALLERY_USERS TO ART_GALLERY_ARTIST;
GRANT EXECUTE ON MANAGE_ORDERS TO ART_GALLERY_ARTIST;

GRANT CONNECT TO ART_GALLERY_CUSTOMER;
GRANT CREATE PROCEDURE TO ART_GALLERY_CUSTOMER;
GRANT CREATE VIEW TO ART_GALLERY_CUSTOMER;
GRANT EXECUTE ON CUSTOMER_PKG TO ART_GALLERY_CUSTOMER;
GRANT EXECUTE ON MANAGE_ARTWORK TO ART_GALLERY_CUSTOMER;
GRANT EXECUTE ON MANAGE_ORDERS TO ART_GALLERY_CUSTOMER;
GRANT EXECUTE ON MANAGE_ARTGALLERY_USERS TO ART_GALLERY_CUSTOMER;




